server:
  port: ${PORT:8080}

spring:
  application:
    name: skillswap
  datasource:
    url:
    ${DB_URL : jdbc:postgresql://localhost:5432/skillswap}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sai}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET:change-this-to-a-long-random-secret-key-in-production-min-256-bits}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    com.skillswap: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
